apiVersion: v1
kind: Service
metadata:
  name: {{ $config.name }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: {{ $appName }}
    version: {{ $version }}
spec:
  type: {{ $config.service.type }}
  ports:
  - name: http
    port: {{ $config.service.port }}
    targetPort: {{ $config.service.targetPort }}
    protocol: TCP
  selector:
    app: {{ $appName }}
    version: {{ $version }}